Repository openshift-kni/oran-o2ims, pull requests merged in 2023-12, with the labels that each got.

#37 Update commands in README.md
  README.md
Labels: approved, lgtm

#36 MGMT-16243: set 'location' property on ResourcePool
  go.mod
  go.sum
  internal/service/resource_pool_fetcher.go
  internal/service/resource_pool_handler_test.go
Labels: approved, lgtm

#38 Fix projection with multiple fields
  internal/search/projector_evaluator.go
  internal/search/projector_evaluator_test.go
  internal/search/selector_evaluator.go
Labels: lgtm

#39 MGMT-16351: Add support for configured extensions
  internal/cmd/server/flags.go
  internal/cmd/server/start_deployment_manager_server.go
  internal/jq/tool.go
  internal/service/deployment_manager_handler.go
  internal/service/deployment_manager_handler_test.go
Labels: lgtm

#41 MGMT-16307: Optimize GraphQL search using filters
  go.mod
  internal/graphql/graphql.go
  internal/graphql/graphql_test.go
  internal/graphql/suite_test.go
  internal/service/resource_fetcher.go
  internal/service/resource_handler.go
  internal/service/resource_handler_test.go
  internal/service/resource_pool_fetcher.go
  internal/service/resource_pool_handler.go
  internal/service/resource_pool_handler_test.go
  internal/service/resource_type_handler.go
Labels: approved, lgtm

#45 docs: update dev env instructions
  docs/dev/env.md
Labels: approved, lgtm

#46 Updates to env.md
  docs/dev/env.md
Labels: approved
