Repository openshift-kni/oran-o2ims, pull requests merged in 2024-04, with the labels that each got.

#79 Add defaults for deployment manager backend URL and token
  api/v1alpha1/orano2ims_types.go
  config/crd/bases/oran.openshift.io_orano2imses.yaml
  config/manager/kustomization.yaml
  internal/cmd/server/start_deployment_manager_server.go
  internal/controllers/orano2ims_controller.go
  internal/controllers/utils/constants.go
  internal/controllers/utils/utils.go
  internal/controllers/utils/utils_test.go
Labels: approved, lgtm

#80 Don't put Go directory at the same level than source
  Containerfile
Labels: approved, lgtm

#75 MGMT-17217: Add AlarmDictionary to resourceTypes API
  README.md
  data/alarms/probable_causes.json
  go.mod
  internal/files/alarms/definitions.json
  internal/files/alarms/probable_causes.json
  internal/files/embed.go
  internal/openapi/spec.yaml
  internal/service/alarm_definition_handler.go
  internal/service/alarm_definition_handler_test.go
  internal/service/alarm_probable_cause_handler_test.go
  internal/service/resource_type_handler.go
  internal/service/resource_type_handler_test.go
Labels: approved

#81 Use assisted installer admin kubeconfig if exists
  internal/service/deployment_manager_handler.go
Labels: approved, lgtm

#85 Reduce numer of parameters of `CreateK8sCR`
  internal/controllers/orano2ims_controller.go
  internal/controllers/utils/utils.go
  internal/controllers/utils/utils_test.go
Labels: approved, lgtm

#87 Remove `oldObject` parameter from `CreateK8sCR`
  internal/controllers/orano2ims_controller.go
  internal/controllers/utils/utils.go
  internal/controllers/utils/utils_test.go
Labels: approved, lgtm

#82 Grant deployment manager server account permissions to read managed clusters and secrets
  Makefile
  bundle/manifests/oran-o2ims.clusterserviceversion.yaml
  bundle/manifests/oran.openshift.io_orano2imses.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/oran-o2ims.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controllers/orano2ims_controller.go
Labels: approved, lgtm

#88 Remove scheme parameter of `CreateK8sCR` and `ORANO2IMSReconciler`
  cmd/main.go
  internal/controllers/orano2ims_controller.go
  internal/controllers/orano2ims_controller_test.go
  internal/controllers/utils/utils.go
  internal/controllers/utils/utils_test.go
Labels: lgtm

#90 Mention that namespaces should be created first
  docs/dev/env_acm.md
Labels: approved, lgtm, ok-to-test

#77 Jenchen/main alert subscription
  internal/cmd/server/start_alarm_subscription_server.go
  internal/controllers/orano2ims_controller.go
  internal/service/alarm_subscription_handler.go
Labels: approved, lgtm
