Repository openshift-kni/oran-o2ims, pull requests merged in 2025-02, with the labels that each got.

#534 CNF-15854: Fix CloudInfo attribute name for global cloud id
  internal/service/resources/api/generated/inventory.generated.go
  internal/service/resources/api/openapi.yaml
  internal/service/resources/serve.go
Labels: approved, lgtm

#536 Add extra labels on the Agent CRs
  .vscode/launch.json
  internal/controllers/provisioningrequest_clusterconfig.go
  internal/controllers/provisioningrequest_clusterconfig_test.go
  internal/controllers/provisioningrequest_controller_test.go
  internal/controllers/provisioningrequest_setup.go
  internal/controllers/suite_test.go
  internal/controllers/utils/constants.go
Labels: approved, lgtm

#537 Fix subscription id field in alarm subscription
  internal/service/alarms/api/generated/alarms.generated.go
  internal/service/alarms/api/openapi.yaml
  internal/service/alarms/internal/db/models/converters.go
Labels: approved, lgtm

#538 Set unique UUID value for deployment managers
  internal/service/resources/collector/collector_k8s.go
Labels: approved, lgtm

#532 Change field include and exclude handling
  go.mod
  internal/search/projector.go
  internal/search/projector_evaluator.go
  internal/search/projector_evaluator_test.go
  internal/search/projector_parser.go
  internal/search/projector_parser_test.go
  internal/search/projector_test.go
  internal/service/alarms/api/generated/alarms.generated.go
  internal/service/alarms/api/openapi.yaml
  internal/service/alarms/api/server.go
  internal/service/alarms/internal/infrastructure/clusterserver/generated/client.gen.go
  internal/service/alarms/internal/infrastructure/clusterserver/generated/mock_generated/mock_client.gen.go
  internal/service/artifacts/api/generated/artifacts.generated.go
  internal/service/artifacts/api/openapi.yaml
  internal/service/artifacts/api/server.go
  internal/service/cluster/api/generated/cluster.generated.go
  internal/service/cluster/api/openapi.yaml
  internal/service/cluster/api/server.go
  internal/service/cluster/collector/collector.go
  internal/service/cluster/db/models/converters.go
  internal/service/common/api/filtering.go
  internal/service/common/api/generated/common.generated.go
  internal/service/common/api/middleware.go
  internal/service/common/api/openapi.yaml
  internal/service/common/api/options.go
  internal/service/common/api/options_test.go
  internal/service/provisioning/api/generated/provisioning.generated.go
  internal/service/provisioning/api/openapi.yaml
  internal/service/provisioning/api/server.go
  internal/service/resources/api/generated/inventory.generated.go
  internal/service/resources/api/openapi.yaml
  internal/service/resources/api/server.go
  internal/service/resources/collector/collector.go
  internal/service/resources/db/models/converters.go
Labels: approved, lgtm

#540 Add unit tests for alarms in cluster server
  internal/service/cluster/api/server.go
  internal/service/cluster/api/server_test.go
  internal/service/cluster/api/suite_test.go
  internal/service/cluster/collector/collector_alarms_test.go
  internal/service/cluster/collector/suite_test.go
  internal/service/cluster/db/repo/generated/mock_repo.generated.go
  internal/service/cluster/db/repo/repository_interface.go
  internal/service/common/repo/repository_interface.go
Labels: approved, lgtm

#543 Fix side effects from duplicates
  internal/service/cluster/collector/collector.go
Labels: approved, lgtm, tide/merge-method-rebase

#542 Fix selector number handling
  internal/search/selector_evaluator.go
  internal/search/selector_evaluator_test.go
  internal/service/alarms/serve.go
  internal/service/artifacts/serve.go
  internal/service/cluster/serve.go
  internal/service/common/api/filtering.go
  internal/service/common/api/filtering_test.go
  internal/service/common/api/suite_test.go
  internal/service/provisioning/serve.go
  internal/service/resources/serve.go
Labels: approved, lgtm

#544 Update IMS endpoint in O-Cloud registration
  internal/controllers/inventory_controller.go
Labels: approved, lgtm

#545 allow trailing slash and middleware refactoring for all servers
  internal/service/alarms/serve.go
  internal/service/artifacts/serve.go
  internal/service/cluster/serve.go
  internal/service/common/api/middleware/errors.go
  internal/service/common/api/middleware/filtering.go
  internal/service/common/api/middleware/filtering_test.go
  internal/service/common/api/middleware/middleware.go
  internal/service/common/api/middleware/middleware_suite_test.go
  internal/service/common/api/utils.go
  internal/service/provisioning/serve.go
  internal/service/resources/serve.go
Labels: approved, lgtm

#546 Add disable-auto-import annotation to prevent stale ManagedCluster re-imported
  internal/controllers/provisioningrequest_clusterinstall.go
  internal/controllers/provisioningrequest_clusterinstall_test.go
  internal/controllers/utils/conditions.go
Labels: approved, lgtm

#548 Remove fulfilled check for hwTemplate changes
  internal/controllers/provisioningrequest_hwprovision.go
Labels: approved, lgtm

#547 update siteconfig operator namespace to open-cluster-management in the sample CRs
  docs/samples/git-setup/clustertemplates/version_4.Y.Z+1/sno-ran-du/clusterinstance-defaults-v1.yaml
  docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v1.yaml
  docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v2.yaml
  docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v3.yaml
  docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-du/clusterinstance-defaults-v4.yaml
  docs/samples/git-setup/clustertemplates/version_4.Y.Z/sno-ran-full-du/clusterinstance-defaults-full-du-v1.yaml
Labels: approved, lgtm, ok-to-test

#549 fix cluster server assertion error
  internal/service/cluster/collector/collector_alarms.go
Labels: approved, lgtm

#550 Artifacts server: Expose cluster provisioning default values - part 1
  .vscode/launch.json
  internal/controllers/inventory_controller.go
  internal/service/artifacts/api/generated/artifacts.generated.go
  internal/service/artifacts/api/openapi.yaml
  internal/service/artifacts/api/server.go
Labels: approved, lgtm

#552 send AlarmAcknowledged notification immediately
  internal/service/alarms/api/server.go
  internal/service/alarms/internal/notifier_provider/notification.go
Labels: approved, lgtm

#554 Artifacts server - default values: separate editable and immutable - part 2
  internal/controllers/utils/utils.go
  internal/controllers/utils/utils_test.go
  internal/service/artifacts/api/generated/artifacts.generated.go
  internal/service/artifacts/api/openapi.yaml
  internal/service/artifacts/api/server.go
Labels: approved, lgtm

#555 Move first fetch all operation inside sync routine
  internal/service/alarms/internal/infrastructure/clusterserver.go
  internal/service/alarms/internal/infrastructure/infrastructure.go
Labels: approved, lgtm

#557 return resourceID with AlarmEventRecord
  internal/service/alarms/api/generated/alarms.generated.go
  internal/service/alarms/api/openapi.yaml
  internal/service/alarms/internal/db/models/converters.go
Labels: approved, lgtm

#553 Update trust bundle procedure and naming
  README.md
  api/inventory/v1alpha1/inventory_types.go
  bundle/manifests/o2ims.oran.openshift.io_inventories.yaml
  bundle/manifests/oran-o2ims.clusterserviceversion.yaml
  config/crd/bases/o2ims.oran.openshift.io_inventories.yaml
  config/manifests/bases/oran-o2ims.clusterserviceversion.yaml
  internal/controllers/inventory_controller.go
  internal/controllers/utils/constants.go
  internal/controllers/utils/utils.go
  vendor/github.com/openshift-kni/oran-o2ims/api/inventory/v1alpha1/inventory_types.go
Labels: approved, lgtm

#561 Skip adding hw labels when hw template is not provided
  internal/controllers/provisioningrequest_clusterconfig.go
  internal/controllers/provisioningrequest_clusterconfig_test.go
Labels: approved, lgtm

#563 Enhance duration logger to include more details
  internal/service/common/api/middleware/middleware.go
Labels: approved, lgtm

#565 Include local-cluster as NodeCluster without extra label
  internal/service/cluster/collector/collector.go
  internal/service/cluster/collector/collector_k8s.go
  internal/service/resources/collector/collector.go
  internal/service/resources/collector/collector_k8s.go
Labels: approved, lgtm

#566 CNF-16511: Loosen the validation check for fulfilled state
  api/provisioning/v1alpha1/provisioningrequest_webhook.go
  api/provisioning/v1alpha1/provisioningrequest_webhook_test.go
  vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_webhook.go
Labels: approved, lgtm

#571 Update OWNERS to add rauhersu and fontivan
  OWNERS_ALIASES
Labels: approved, lgtm

#572 Remove disable-auto-import annotation after the installation is complete
  .vscode/launch.json
  internal/controllers/provisioningrequest_clusterinstall.go
  internal/controllers/provisioningrequest_controller_test.go
Labels: approved, lgtm

#570 Display the provisioning failure when multiple errors occur
  internal/controllers/provisioningrequest_controller.go
  internal/controllers/provisioningrequest_controller_test.go
Labels: approved, lgtm

#573 CNF-16727: improve alarms notification reliability with an outbox and event-driven with pg listen/notify
  internal/service/alarms/api/server.go
  internal/service/alarms/internal/db/migrations/000001_create_data_change_event_table.down.sql
  internal/service/alarms/internal/db/migrations/000001_create_data_change_event_table.up.sql
  internal/service/alarms/internal/db/migrations/000002_create_alarm_event_record_table.down.sql
  internal/service/alarms/internal/db/migrations/000002_create_alarm_event_record_table.up.sql
  internal/service/alarms/internal/db/migrations/000003_create_alarm_subscription_info_table.down.sql
  internal/service/alarms/internal/db/migrations/000003_create_alarm_subscription_info_table.up.sql
  internal/service/alarms/internal/db/migrations/000004_create_alarm_service_configuration_table.down.sql
  internal/service/alarms/internal/db/migrations/000004_create_alarm_service_configuration_table.up.sql
  internal/service/alarms/internal/db/models/alarm_event_record.go
  internal/service/alarms/internal/db/models/converters.go
  internal/service/alarms/internal/db/repo/alarms_repository.go
  internal/service/alarms/internal/db/repo/alarms_repository_interface.go
  internal/service/alarms/internal/db/repo/alarms_repository_test.go
  internal/service/alarms/internal/db/repo/generated/mock_repo.generated.go
  internal/service/alarms/internal/listener/pg_listener.go
  internal/service/alarms/internal/notifier_provider/notification.go
  internal/service/alarms/serve.go
  internal/service/common/db/models/notification_cursor.go
  internal/service/common/listener/pg_listener_manager.go
  internal/service/common/repo/repository.go
  internal/service/common/repo/repository_interface.go
Labels: approved, lgtm

#579 CNF-16878: Add client certificate binding support (RFC8705)
  README.md
  api/inventory/v1alpha1/inventory_types.go
  bundle/manifests/o2ims.oran.openshift.io_inventories.yaml
  bundle/manifests/oran-o2ims.clusterserviceversion.yaml
  config/crd/bases/o2ims.oran.openshift.io_inventories.yaml
  config/manifests/bases/oran-o2ims.clusterserviceversion.yaml
  internal/controllers/utils/utils.go
  internal/service/common/auth/auth_oauth.go
  internal/service/common/auth/auth_rfc8705.go
  internal/service/common/auth/auth_rfc8705_test.go
  internal/service/common/auth/middleware.go
  internal/service/common/utils/config.go
  vendor/github.com/openshift-kni/oran-o2ims/api/inventory/v1alpha1/inventory_types.go
Labels: approved, lgtm

#577 CNF-16737: Validate the ClusterInstance defaults ConfigMap against the ClusterInstance CRD schema
  .vscode/launch.json
  api/provisioning/v1alpha1/provisioningrequest_validation.go
  api/provisioning/v1alpha1/provisioningrquest_validation_test.go
  bundle/manifests/oran-o2ims.clusterserviceversion.yaml
  config/rbac/role.yaml
  go.mod
  internal/cmd/operator/start_controller_manager.go
  internal/controllers/clustertemplate_controller.go
  internal/controllers/clustertemplate_controller_test.go
  internal/controllers/provisioningrequest_clusterconfig_test.go
  internal/controllers/provisioningrequest_resourcecreation.go
  internal/controllers/suite_test.go
  internal/controllers/utils/constants.go
  internal/controllers/utils/provision.go
  internal/controllers/utils/provision_test.go
  internal/controllers/utils/test_common.go
  vendor/github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1/provisioningrequest_validation.go
Labels: approved, lgtm

#578 Update dependabot to ignore golang.org/x/oauth2 updates due to go 1.23
  .github/dependabot.yml
Labels: approved, lgtm

#582 Fix the removal of required fields from ClusterInstance schema
  internal/controllers/utils/provision.go
  internal/controllers/utils/provision_test.go
  internal/controllers/utils/test_common.go
Labels: approved, lgtm
